# Generated by Django 5.1.3 on 2025-01-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassApp', '0002_alter_student_registration_number_alter_unit_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='units',
            field=models.ManyToManyField(blank=True, to='ClassApp.unit'),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='unit',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
